configfile: "config/sample_info.yaml"
configfile: "config/index_and_anno.yaml"
configfile: "config/software_setting.yaml"
configfile: "config/deeptools.yaml"
configfile: "config/binding_motif.yaml"

include: "rules/concat_fastq.smk"
include: "rules/fastp.smk"
include: "rules/bwa_mapping.smk"
include: "rules/callpeak.smk"
include: "rules/deeptools.smk"
include: "rules/binding_motif.smk"
include: "rules/peak_anno.smk"


rule all:
    input:
        # bwa_mapping
        expand("results/bwa_mapping/{sample}.flagstats.txt", sample=config["samples"]),

        # callpeak
        [f"results/macs_callpeak/{peak_type}/{peak}_peaks.{peak_type}Peak" for peak_type in config["peaks"] for peak in config["peaks"][peak_type]],
        "results/FRiP.pdf",

        # deeptools
        expand("results/deeptools_heatmaps/{heatmap}.heatmap.pdf", heatmap=config["deeptools_heatmaps"]),
        expand("results/BigWig/{sample}.bw", sample=config["bws"]),

        # binding_motif
        expand("results/meme/{job}", job=config["binding-motif-jobs"]),

        # peak_anno
        [f"results/peak_anno/{peak_type}/{peak}/{peak}.min-signal-0.oryzabase_anno.xlsx" for peak_type in config["peaks"] for peak in config["peaks"][peak_type]],
        [f"results/peak_anno/{peak_type}/{peak}/{peak}.feature_bar.svg" for peak_type in config["peaks"] for peak in config["peaks"][peak_type]]

