# description: This file contains functions for annotating peaks.
# author: panyq357
# date: 2023-11-02

library(rtracklayer)
library(GenomicFeatures)
library(GenomicRanges)
library(ggplot2)

config <- list(
    gtf = snakemake@input$gtf,
    peak = snakemake@input$peak,
    peak_to_gene = snakemake@output$peak_to_gene,
    feature_bar = snakemake@output$feature_bar,
    anno = snakemake@params$anno
)

main <- function(){

    gtf_gr <- rtracklayer::import(config$gtf)

    tx_to_gene <- make_tx_to_gene(gtf_gr)

    txdb <- makeTxDbFromGRanges(gtf_gr)

    feature_grl <- split(gtf_gr, gtf_gr$type)

    feature_grl <- feature_grl[c("transcript", "exon", "CDS", "five_prime_utr", "three_prime_utr")]

    feature_grl[["intron"]] <- get_feature_gr(txdb, "intron")
    feature_grl[["promoter_minus_2000_plus_200"]] <- get_promoter_gr(txdb)  # Default promoter is upstream 2kb downstream 200bp.
    feature_grl[["three_prime_500"]] <- flank(feature_grl[["transcript"]], 500, start=F)
    feature_grl[["three_prime_500"]]$type <- "three_prime_500"

    for (feature in names(feature_grl)) {
        feature_grl[[feature]]$gene_id <- tx_to_gene[feature_grl[[feature]]$transcript_id]
    }

    peak_gr <- read_peak(config$peak)
        
    feature_overlap_matrix <- get_feature_overlap_matrix(peak_gr, feature_grl, anno=config$anno)

    svg(config$feature_bar, width=6, height=3)
        print(plot_feature_bar(feature_overlap_matrix, config$feature_bar))
    dev.off()

    write.csv(cbind(as.data.frame(granges(peak_gr)), mcols(peak_gr), feature_overlap_matrix), config$peak_to_gene, row.names=FALSE)
}

#' Read-in peak files
#'
#' Based on file extension, use readRDS to read Diffbind report rds, or use read_macs_xls to read MACS xls.
#' @examples
#' peak_gr1 <- read_peak("results/macs_callpeak/sample1/sample1_peaks.xls")
#' peak_gr2 <- read_peak("results/diffbind_analyze/job2/job2.report.rds")
read_peak <- function(path) {

    get_ext <- function(path) {
        path_split <- strsplit(path, "\\.")[[1]]
        ext <- path_split[[length(path_split)]]
        return(ext)
    }

    read_macs_xls <- function (macs_xls_path) {
        df <- read.table(macs_xls_path, header=T, check.names=F)
        gr <- makeGRangesFromDataFrame(df, keep.extra.columns=TRUE)
        return(gr)
    }

    peak_ext <- get_ext(path)

    if (peak_ext == "rds") {
        peak_gr <- readRDS(path)
    } else if (peak_ext == "xls") {
        peak_gr <- read_macs_xls(path)
    } else {
        stop(sprintf("Unrecognized peak file type '%s'", peak_ext))
    }
    return(peak_gr)
}

#' Make a vector mapping transcript_id to gene_id
#'
#' @examples
#' tx_to_gene <- make_tx_to_gene(ref_gr)
#' tx_to_gene["AT5G62580.2"]
make_tx_to_gene <- function(ref_gr) {
    tx_to_gene <- with(
        data = subset(ref_gr, !is.na(gene_id) & !is.na(transcript_id)),
        expr = setNames(gene_id, transcript_id)
    )
    tx_to_gene <- tx_to_gene[!duplicated(names(tx_to_gene))]
    return(tx_to_gene)
}


get_feature_gr <- function(txdb, type) {

    fun <- list(
        "intron" = "intronsByTranscript",
        "five_prime_utr" = "fiveUTRsByTranscript",
        "three_prime_utr" = "threeUTRsByTranscript"
    )

    #' Convert GRangesList generated by "?transcriptsBy" to GRanges with mcols
    #'
    #' In get_feature_gr, txdb and ?transcriptsBy functions were utilized to get
    #' intron, five_prime_utr and three_prime_utr. with use.names=T argument,
    #' ?transcriptsBy functions generate GRangesList with transcript_id as its names.
    #' It needs to be convert to a GRanges for downstream feature overlapping.
    grl_to_gr_with_mcols <- function(grl, type, ref_gr, source="calculated", score=NA, phase=NA) {
        
        gr <- unlist(grl)
        mcols(gr) <- NULL  # functions like "fiveUTRsByTranscript" may produce extra mcols.
        gr$source <- source
        gr$type <- type
        gr$score <- score
        gr$phase <- phase
        gr$transcript_id <- rep(names(grl), elementNROWS(grl))
        return(gr)
    }

    grl <- get(fun[[type]])(txdb, use.names=T)
    gr <- grl_to_gr_with_mcols(grl, type, txdb_gr)
    names(gr) <- NULL  # If not NULL, will be corresponding transcript_id.
    return(gr)
}

#' Arguments:
#'   type will be presented in returned gr's mcols, can be specified with any string.
#'   ... will be passed to "promoters" function. e.g. upstream, downstream ...
get_promoter_gr <- function(txdb, type="promoter_minus_2000_plus_200", ...) {

    # Unlike "?transcriptsBy", "promoters" applied to TxDb produced a GRanges rather then GRangesList.
    gr <- promoters(txdb, use.names=T, ...)
    mcols(gr) <- NULL
    gr$source <- "calculated"
    gr$type <- type
    gr$score <- NA
    gr$phase <- NA
    gr$transcript_id <- names(gr)
    names(gr) <- NULL
    return(gr)
}

get_feature_overlap_matrix <- function (peak_gr, feature_grl, anno) {

    names(peak_gr) <- NULL

    feature_overlap_matrix <- matrix(nrow=length(peak_gr), ncol=length(feature_grl))
    colnames(feature_overlap_matrix) <- names(feature_grl)

    feature_overlap_list <- lapply(feature_grl, function(x) findOverlaps(peak_gr, x))

    for (name in names(feature_grl)) {
        overlap <- findOverlaps(peak_gr, feature_grl[[name]])
        peak_to_anno <- split(mcols(feature_grl[[name]])[[anno]][overlap@to], overlap@from) |>
            lapply(unique) |>
            lapply(paste, collapse=",") |>
            unlist()  # Because of split(), type of names of this vector is character.
        feature_overlap_matrix[as.integer(names(peak_to_anno)), name] <- peak_to_anno
    }

    return(feature_overlap_matrix)
}

plot_feature_bar <- function(feature_overlap_matrix, out_path) {
    percentages <- sapply(as.data.frame(feature_overlap_matrix), function(x) {sum(!is.na(x)) / length(x)})
    plot <- ggplot() +
        geom_col(aes(x = percentages, y = names(percentages)), width=.6) +
        scale_x_continuous(limits=c(0, 1), breaks=seq(0, 1, length.out=5), labels=c("0%", "25%", "50%", "75%", "100%")) +
        labs(x = "Percentage", y = "Features")
    return(plot)
}

main()

