binding-motif-jobs:
  Mock-1-with-input-top-1000-radius-50:
    peak: JA-1-with-input
    top: 1000
    radius: 50
  Mock-2-with-input-top-1000-radius-50:
    peak: JA-2-with-input
    top: 1000
    radius: 50
  Mock-3-with-input-top-1000-radius-50:
    peak: JA-3-with-input
    top: 1000
    radius: 50
