macs_format: "BAMPE"

# TAIR10: 120000000, IRGSP-1.0: 370000000
mappable_genome_size: 370000000

peaks:
  DAP_1-with-input:
    type: "narrow"
    ip: "DAP_1"
    input: "DAP_control_1"
  DAP_2-with-input:
    type: "narrow"
    ip: "DAP_2"
    input: "DAP_control_2"
  DAP_1-no-input:
    type: "narrow"
    ip: "DAP_1"
  DAP_2-no-input:
    type: "narrow"
    ip: "DAP_2"
