
transcript_bed: "/home/panyq/Tools/index-scripts/os/rap-db/results/custom_bed/transcript.bed"

tss-to-tes-jobs:
#  compare:  # format: "results/bamCompare/{peak_with_input}-compare.bw"
#    - "results/bamCompare/DAP_1-with-input-compare.bw"
#    - "results/bamCompare/DAP_2-with-input-compare.bw"
  coverage:  # format: "results/bamCoverage/{sample}.bw" 
    - "results/bamCoverage/PC48.bw"
    - "results/bamCoverage/PC54.bw"
    - "results/bamCoverage/GFP.bw"
    
